version: "3.7"

services:
  app:
    image: gcr.io/gke-test-287910/folks-ui:v0.0.2
    ports:
      - "8000:8000"
    environment:
      AP_PORT: 8000
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/top.html:/var/www/static/index.html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app